import { createHash, randomUUID } from 'node:crypto';
import { mkdir, readFile, rm, stat, writeFile } from 'node:fs/promises';
import { dirname, join, resolve, sep } from 'node:path';

/**
 * Object storage (docs/architecture.md §2).
 *
 * Behind an interface because the production driver is undecided: MinIO is
 * AGPLv3, which reaches a hosted SaaS, so the likely choice is SeaweedFS
 * (Apache-2.0) with S3/R2 as an optional paid alternative. Nothing above this
 * interface knows or cares.
 *
 * SECURITY: keys are always tenant-prefixed and are generated server-side.
 * A filename supplied by a user never becomes part of a path.
 */

export interface StoredObject {
  readonly key: string;
  readonly size: number;
  readonly checksum: string;
}

export interface StorageDriver {
  put(key: string, bytes: Uint8Array): Promise<StoredObject>;
  get(key: string): Promise<Uint8Array>;
  delete(key: string): Promise<void>;
  exists(key: string): Promise<boolean>;
}

export class StorageError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'StorageError';
  }
}

/**
 * Build a storage key.
 *
 * The user's filename is used ONLY to recover an extension, and that extension
 * is allowlisted to `[a-z0-9]{1,8}`. The body of the key is a server-generated
 * UUID. This means no user-controlled string ever reaches the filesystem, so
 * traversal (`../`), absolute paths, NUL bytes, Windows device names and
 * case-collision tricks are all impossible by construction rather than by
 * filtering.
 */
export function buildStorageKey(params: {
  organizationId: string;
  sourceId: string;
  filename: string;
  kind: 'raw' | 'text';
}): string {
  const dot = params.filename.lastIndexOf('.');
  const rawExtension = dot === -1 ? '' : params.filename.slice(dot + 1).toLowerCase();
  const extension = /^[a-z0-9]{1,8}$/.test(rawExtension) ? `.${rawExtension}` : '';

  return `org/${params.organizationId}/source/${params.sourceId}/${params.kind}/${randomUUID()}${extension}`;
}

/** Keys are generated by buildStorageKey; this rejects anything that is not. */
const KEY_PATTERN =
  /^org\/[0-9a-f-]{36}\/source\/[0-9a-f-]{36}\/(raw|text)\/[0-9a-f-]{36}(\.[a-z0-9]{1,8})?$/;

export function assertValidKey(key: string): void {
  if (!KEY_PATTERN.test(key)) {
    throw new StorageError('Invalid storage key.');
  }
}

/** Extract the owning organization from a key, so access can be re-checked. */
export function organizationOfKey(key: string): string | null {
  const match = /^org\/([0-9a-f-]{36})\//.exec(key);
  return match?.[1] ?? null;
}

export function sha256(bytes: Uint8Array): string {
  return createHash('sha256').update(bytes).digest('hex');
}

/**
 * Local filesystem driver, for development.
 *
 * Production uses an S3-compatible driver; this exists so the platform runs
 * without object storage infrastructure. It is a real implementation, not a
 * stub — it genuinely persists, reads back and deletes.
 */
export class LocalStorageDriver implements StorageDriver {
  private readonly root: string;

  constructor(rootPath: string) {
    this.root = resolve(rootPath);
  }

  /**
   * Resolve a key to an absolute path, then verify the result is still inside
   * the root. Belt and braces: assertValidKey should already have made
   * traversal impossible, but a containment check costs nothing and catches
   * any future key format that is looser than intended.
   */
  private pathFor(key: string): string {
    assertValidKey(key);
    const full = resolve(join(this.root, key));
    if (full !== this.root && !full.startsWith(this.root + sep)) {
      throw new StorageError('Resolved path escaped the storage root.');
    }
    return full;
  }

  async put(key: string, bytes: Uint8Array): Promise<StoredObject> {
    const path = this.pathFor(key);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, bytes);
    return { key, size: bytes.byteLength, checksum: sha256(bytes) };
  }

  async get(key: string): Promise<Uint8Array> {
    try {
      return new Uint8Array(await readFile(this.pathFor(key)));
    } catch (error) {
      if (error instanceof StorageError) throw error;
      throw new StorageError('Stored object not found.');
    }
  }

  async delete(key: string): Promise<void> {
    await rm(this.pathFor(key), { force: true });
  }

  async exists(key: string): Promise<boolean> {
    try {
      await stat(this.pathFor(key));
      return true;
    } catch {
      return false;
    }
  }
}
