-- =============================================================================
-- 0005_credentials — Moka Credentials vault
--
-- Run as: moka_migrator
--
-- Stores provider API keys under envelope encryption (docs/security.md §3.1):
--
--   ENCRYPTION_KEY (root KEK)
--      └─ wraps ─▶ organizations.dek_wrapped (per-org DEK)
--                     └─ encrypts ─▶ credentials.ciphertext
--
-- `id` has NO DEFAULT, deliberately. The ciphertext's AES-GCM Additional
-- Authenticated Data binds it to (organization_id, id, provider_id), so the id
-- must exist before the secret is encrypted. A database-generated default
-- would mean encrypting against an id we do not yet know.
--
-- That binding is what makes row tampering fail closed: a ciphertext copied
-- into another organization's row, relabelled to another provider, or moved to
-- a different credential id will not decrypt. It does not merely fail an
-- application check — the cryptography itself refuses.
-- =============================================================================

CREATE TABLE credentials (
  -- No DEFAULT: generated by the application before encryption. See above.
  id              uuid PRIMARY KEY,
  organization_id uuid        NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
  provider_id     text        NOT NULL,
  name            text        NOT NULL,

  -- Envelope-encrypted secret. base64, matching organizations.dek_wrapped.
  -- The plaintext key is never stored in any form, anywhere.
  ciphertext      text        NOT NULL,
  iv              text        NOT NULL,
  auth_tag        text        NOT NULL,

  -- Non-reversible SHA-256 prefix. Used to detect a duplicate key being added
  -- twice without ever comparing plaintext.
  fingerprint     text        NOT NULL,
  -- Trailing characters only, for display. Never the leading characters,
  -- which carry the provider prefix and narrow a brute-force search.
  last_four       text        NOT NULL,

  -- Optional BYOK endpoint. User-supplied, so it is SSRF-validated through
  -- @moka/net before it is ever stored, and again before it is used.
  base_url        text,

  status          text        NOT NULL DEFAULT 'active',
  is_default      boolean     NOT NULL DEFAULT false,

  last_used_at    timestamptz,
  last_tested_at  timestamptz,
  last_test_ok    boolean,
  rotated_at      timestamptz,
  revoked_at      timestamptz,

  created_by      uuid        REFERENCES users (id) ON DELETE SET NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT credentials_status_valid CHECK (status IN ('active', 'disabled', 'revoked')),
  CONSTRAINT credentials_last_four_short CHECK (length(last_four) <= 8),
  -- A revoked credential must have a revocation time, so "is it revoked?" has
  -- exactly one answer rather than two fields that can disagree.
  CONSTRAINT credentials_revoked_consistent CHECK (
    (status = 'revoked') = (revoked_at IS NOT NULL)
  )
);

CREATE INDEX credentials_org_created_idx  ON credentials (organization_id, created_at DESC);
CREATE INDEX credentials_org_provider_idx ON credentials (organization_id, provider_id);

-- The same key added twice to one organization is a mistake, not two credentials.
CREATE UNIQUE INDEX credentials_org_provider_fingerprint_unique
  ON credentials (organization_id, provider_id, fingerprint);

-- At most one default per provider per organization, enforced by the database
-- rather than by application convention.
CREATE UNIQUE INDEX credentials_one_default_per_provider
  ON credentials (organization_id, provider_id)
  WHERE is_default AND status = 'active';

-- =============================================================================
-- ROW-LEVEL SECURITY
-- =============================================================================

ALTER TABLE credentials ENABLE ROW LEVEL SECURITY;
ALTER TABLE credentials FORCE  ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON credentials
  USING      (organization_id = current_org_id())
  WITH CHECK (organization_id = current_org_id());

-- DELETE is granted: "delete my API key" is a legitimate request, and a vault
-- that can only soft-delete cannot honour it.
GRANT SELECT, INSERT, UPDATE, DELETE ON credentials TO moka_app;
